// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});


function defineConfig(arg0: { schema: string; migrations: { path: string; }; datasource: { url: string | undefined; }; }) {
  throw new Error("Function not implemented.");
}

